version: "3.6"
services:
  steampipe:
    build: .
    ports:
      - "9193:9193"
    command: ["service", "start", "--foreground"]
    restart: unless-stopped
    volumes:
      - './internal:/home/steampipe/.steampipe/internal'
      - './logs:/home/steampipe/.steampipe/logs'
    environment:
      STEAMPIPE_DATABASE_PASSWORD: "$STEAMPIPE_DATABASE_PASSWORD"
      AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
      AWS_REGION: eu-west-1
      XERO_CLIENT_ID: "$XERO_CLIENT_ID"
      XERO_CLIENT_SECRET: "$XERO_CLIENT_SECRET"
      XERO_OAUTH_CODE: "$XERO_OAUTH_CODE"
